name: gdi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - bedtools
#  - iqtree
#  - bcftools
#  - htslib
#  - pyqt5
  - python=3.8
  - pyqt
  - git
  - ete3
  - biopython >=1.70
  - click
  - click-config-file
  - coloredlogs
  - ete3
  - jsonschema ==3.2.0
  - numpy
  - pandas >=1.0.0
#  - pybedtools
  - pymysql
  - pyroaring
  - pytest
  - python >=3.7,<3.9
  - pyvcf
  - pyyaml
  - requests
#  - scikit-bio
  - snakemake
  - sourmash
  - sqlalchemy
  - pip
  - pip:
    - biocommons.seqrepo
    - ga4gh.vrs[extras] ==0.6.2
