name: gdi
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pyqt
  - bedtools
  - fasttree
  - iqtree
  - bcftools >= 1.13
  - htslib
  - jupyterlab
  - matplotlib
  - snpeff
