name: thesis-index
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - bitarray
  - biopython[version='>=1.70']
  - pandas[version='>=1.0.0']
  - pytest
  - pyvcf
  - sqlalchemy
  - htslib
  - fasttree
  - ete3
  - click
  - pymysql
  - mysql
  - click-config-file
  - iqtree
  - pyroaring
