# An example configuration file defining the reference genome and samples
reference: input-data/reference.fasta
samples: config/samples.tsv
include_kmer: True
include_mlst: True
include_snpeff: False
sourmash_params: k=31,scaled=1000
reads_mincov: 10
reads_minqual: 100
reads_subsample: 1
