# An example configuration file defining the reference genome and samples
reference: input-data/NC_011083-5000-snpeff.gbk.gz
samples: config/samples-all-data.tsv
include_kmer: True
include_mlst: False
include_snpeff: True
sourmash_params: k=31,scaled=1000
reads_mincov: 5
reads_minqual: 100
reads_subsample: 1
