# An example configuration file defining the reference genome and samples
reference: input-data/NC_011083-5000-snpeff.gbk.gz
samples: config/samples-snpeff.tsv
include_kmer: True
include_mlst: True
sourmash_params: k=31,scaled=1000
